# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-pod
#   labels:
#     owner: john
#     # Missing 'environment' and 'creator' labels
# spec:
#   containers:
#   - name: nginx
#     image: nginx

apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    owner: 
    environment: dev
    creator: admin
spec:
  containers:
  - name: nginx
    image: nginx:production

